project:
  type: website

website:
  site-url: https://schlaipferm.github.io
  title: "CARBONIQUE"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




babelquarto:
  languagecodes:
  - name: fr
    text: "Français"
  - name: en
    text: "English"
  mainlanguage: 'fr'
  languages: ['en']
title-en: "CARBONIQUE"
description-en: description in en
author-en: author in en
lang: fr
