project:
  type: website

website:
  site-url: https://schlaipferm.github.io
  title: "CARBONIQUE"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - about.qmd
      
sidebar:
    - id: home
      title: "Home/Accueil"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Home/Accueil
        - href: Research.qmd
          text: Research/Recherche
        - href: People.qmd
          text: People/Équipe
        - href: Publications.qmd
          text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




babelquarto:
  languagecodes:
  - name: fr
    text: "Français"
  - name: en
    text: "English"
  mainlanguage: 'fr'
  languages: ['en']
title-en: "CARBONIQUE"
description-en: description in en
author-en: author in en
lang: fr
