project:
  type: website
  output-dir: docs

website:
  cookie-consent: true
  site-url: https://schlaipferm.github.io
  title: "CARBONIQUE"
  navbar:
    left:
      - documentation.qmd
      - data.qmd
      - news.qmd

    right:
      - icon: github
        href: https://github.com/carboni-que
        aria-label: Quarto GitHub
      - icon: box-arrow-in-right
        href: https://carbonique-signin-auth.web.app/index.html
        aria-label: Login
  sidebar:
    - id: accueil
      title: "Accueil"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Accueil
        - href: research.qmd
          text: Recherche
        - href: people.qmd
          text: Équipe
        - href: join.qmd
          text: Rejoignez-nous
        # - href: Publications.qmd
        #   text: Publications
        - href: partners.qmd
          text: Partenaires
    - id: home
      title: "Home"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Home
        - href: research.qmd
          text: Research
        - href: people.qmd
          text: People
        # - href: Publications.qmd
        #   text: Publications
        - href: join.qmd
          text: Join us!
        - href: partners.qmd
          text: Partners

format:
  html:
    theme:
      - sandstone
      - custom.scss
    css: styles.css
    toc: true




babelquarto:
  languagecodes:
  - name: fr
    text: "Français"
  - name: en
    text: "English"
  mainlanguage: 'fr'
  languages: ['en']
title-en: "CARBONIQUE"
description-en: description in en
author-en: author in en
lang: fr
