project:
  type: website

website:
  site-url: https://schlaipferm.github.io
  title: "CARBONIQUE"
  navbar:
    left:
      - documentation.qmd
      - data.qmd
    right:
      - icon: github
        href: https://github.com/carboni-que
        aria-label: Quarto GitHub
  sidebar:
    - id: accueil
      title: "Accueil"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Accueil
        - href: research.qmd
          text: Recherche
        - href: people.qmd
          text: Équipe
        # - href: Publications.qmd
        #   text: Publications
    - id: home
      title: "Home"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Home
        - href: research.qmd
          text: Research
        - href: people.qmd
          text: People
        # - href: Publications.qmd
        #   text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




babelquarto:
  languagecodes:
  - name: fr
    text: "Français"
  - name: en
    text: "English"
  mainlanguage: 'fr'
  languages: ['en']
title-en: "CARBONIQUE"
description-en: description in en
author-en: author in en
lang: fr
