---
title: "Research"
---

This research is a unique opportunity to improve understanding and prediction of the potential role of wetlands as Nature-based Climate Solutions (NbCS). Our project is the largest and most comprehensive and integrative assessment of wetland carbon dynamics and balances in Canada to date and will provide much needed new data to carry out robust, evidence-based assessments of the capacity of natural and disturbed wetlands to mitigate climate change. This research is unique in integrating all components of the C cycle to provide a robust and realistic assessment of C and GHG budgets across wetland ecosystems that are of particular importance in the Canadian landscape. By integrating lateral and vertical fluxes and combining them with soil core observations, our work will allow us to develop reliable estimates of Net Ecosystem Carbon Balance (NECB) and assess the long-term C dynamics and the impacts of anthropogenic disturbances on wetlands. Our research and collaborations also provide a unique opportunity for improving wetland biogeochemical models. 

Specifically, our work will further improve wetland C cycle science in Quebec and Canada, provide key information for policy makers, guide the management and restoration of wetlands for different levels of governments, contribute to climate change mitigation accounting, and support climate action initiatives across regional, provincial, and federal levels. Furthermore, by improving biogeochemical models, we will contribute to better quantifying C emissions and removals from land-use change and management of wetlands in Canada, which will ultimately reduce uncertainty in Canadian inventory reporting.
<br>
<br>


## Objective 1: Quantifying C sequestration in soils and biomass
Objective 1 aims to document the mid-(decadal) and long-term (centennial) C sequestration potential in wetland soils and biomass under natural and disturbed conditions. C stocks (kg m-2) and long-term C sequestration rates (kg m-2 yr-1) will be quantified under natural and disturbed conditions in the four wetland categories (open bogs, forested bogs, forested swamps and coastal marshes) to estimate the impact of disturbances, primarily related to drainage, on their C sequestration potential.  We will also compare whether the C budgets measured by vertical and horizontal fluxes (Objective 2 and 3) corresponds to the variation of soil C sequestration through the <150-year time period. The results of these comparisons are of importance both technically (i.e., validating the closure of the C budget) and scientifically (i.e., exploring the long-term vs. short-term dynamics of the C budgets), and will result in: 1) a synthesis of C stock and sequestration rates in the soil and plant biomass of natural and disturbed wetlands across southern Quebec, and 2) the development of a decision tool for hotspots of C in wetland conservation. We expect that while natural wetlands will act as net C sinks, disturbed wetlands may be C sources, with the magnitude of the source increasing with the level of disturbance.

## Objective 2: Quantifying vertical (gaseous) C and GHG (CO2, CH4, and N2O) fluxes
Objective 2 aims to measure year-round C and GHG fluxes to quantify vertical (gaseous) fluxes of the NECB over natural and disturbed wetlands, and evaluate diurnal, seasonal, and interannual variability in fluxes driven by climatic and environmental drivers. An eddy covariance (EC) tower will be installed in each wetland type both natural and disturbed for a total of 8 towers supported by the MELCCFP. A 9th tower will be contributed from McGill in a restored site near Lac Saint-Pierre (LSP). These towers will measure vertical (gaseous) fluxes including net CO2 exchange (NEP, which is the balance between gross ecosystem productivity and ecosystem respiration) and net CH4 exchange (the balance between methanogenesis and methanotrophy). Continuous, year-round EC observations will provide robust annual vertical C and GHG budgets for each site. While we expect lower CH4 emissions from disturbed (i.e., drained wetlands), we anticipate that this will be outweighed by significantly higher CO2 emissions, making the disturbed sites a larger net GHG source than the natural wetlands. For each site, the impact of disturbance on fluxes will also be investigated. Additionally, the quasi-continuous nature of these C and GHG flux measurements coupled with ancillary measurements (e.g., radiation, temperature, relative humidity, soil moisture, water table depth) will allow us to investigate the dominant controls on GHG fluxes and assess how C fluxes will respond to a changing climate and intensifying disturbance regimes.

## Objective 3: Quantifying and modeling the hydrologic balance and lateral (aquatic) C fluxes
Objective 3 will quantify the hydrologic balance and the lateral C export from the natural and disturbed wetland ecosystems in a series of detailed case studies that will greatly enhance our understating of the mechanisms and pathways underlying the processes in each of these systems. This will require a detailed characterization of the water balance and the hydrologic connectivity with surface and groundwater in each of the target ecosystems. Additionally, a detailed biogeochemical quantification (including dissolved organic carbon (DOC), dissolved inorganic carbon (DIC), partitional pressure of CO2 and CH4 (pCO2 and pCH4, respectively), and water chemistry) of the outflows of the studied wetlands including interstitial and groundwater will be conducted. This will allow us to quantify the net lateral C and GHG budgets of natural and disturbed wetlands across southern Quebec. These comparative case studies will allow us to derive general patterns of C export based on landscape and hydrologic features, which will be used to upscale C export at a regional level. Mechanistic models of lateral C export will also be developed to assess how climate-induced change and human disturbance may impact this important aspect of the wetland ecosystem C balance. We expect that C export will comprise a significant yet varying component of the C budget of the different wetland ecosystems, but that in all cases, these lateral C fluxes will be essential for closure of the NECB.

## Objective 4: Generating an integrative understanding of C and GHG dynamic in disturbed/undisturbed landscapes
Objective 4 integrates all findings from Objectives 1-3 to provide a complete picture of the NECB and net GHG budget for each ecosystem. We will also leverage observations and modeling to predict future NECB across wetland types. This Objective will provide an integrated picture of the current and future C and GHG budget of each wetland type and disturbance class. We expect to see significant differences in NECB across sites, with the greatest difference in NECB being between natural and disturbed wetlands. We also expect that by leveraging observations to incorporate new processes into wetland biogeochemical models (i.e., lateral C fluxes), we will be able to better predict current and future wetland NECB.